plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'com.electricmayhem.robokart.controllerlib'
    compileSdk 35

    defaultConfig {
        minSdk 30
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    implementation("org.eclipse.zenoh:zenoh-java-android:1.7.2")
    implementation libs.appcompat
    implementation libs.material
    androidTestImplementation libs.espresso.core
}